/* automatically generated by rust-bindgen 0.72.1 */

#[derive(PartialEq, Copy, Clone, Hash, Debug, Default)]
#[repr(transparent)]
pub struct __BindgenFloat16(pub u16);
pub const __WORDSIZE: u32 = 64;
pub const __has_safe_buffers: u32 = 1;
pub const __DARWIN_ONLY_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const __DARWIN_ONLY_VERS_1050: u32 = 1;
pub const __DARWIN_UNIX03: u32 = 1;
pub const __DARWIN_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_VERS_1050: u32 = 1;
pub const __DARWIN_NON_CANCELABLE: u32 = 0;
pub const __DARWIN_SUF_EXTSN: &[u8; 14] = b"$DARWIN_EXTSN\0";
pub const __DARWIN_C_ANSI: u32 = 4096;
pub const __DARWIN_C_FULL: u32 = 900000;
pub const __DARWIN_C_LEVEL: u32 = 900000;
pub const __STDC_WANT_LIB_EXT1__: u32 = 1;
pub const __DARWIN_NO_LONG_LONG: u32 = 0;
pub const _DARWIN_FEATURE_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_VERS_1050: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const _DARWIN_FEATURE_UNIX_CONFORMANCE: u32 = 3;
pub const __has_ptrcheck: u32 = 0;
pub const USE_CLANG_TYPES: u32 = 0;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const INT64_MAX: u64 = 9223372036854775807;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT64_MIN: i64 = -9223372036854775808;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const UINT64_MAX: i32 = -1;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST64_MIN: i64 = -9223372036854775808;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const INT_LEAST64_MAX: u64 = 9223372036854775807;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const UINT_LEAST64_MAX: i32 = -1;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i32 = -32768;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST64_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u32 = 32767;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const INT_FAST64_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: u32 = 65535;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const UINT_FAST64_MAX: i32 = -1;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const UINTPTR_MAX: i32 = -1;
pub const SIZE_MAX: i32 = -1;
pub const RSIZE_MAX: i32 = -1;
pub const WINT_MIN: i32 = -2147483648;
pub const WINT_MAX: u32 = 2147483647;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub type int_least8_t = i8;
pub type int_least16_t = i16;
pub type int_least32_t = i32;
pub type int_least64_t = i64;
pub type uint_least8_t = u8;
pub type uint_least16_t = u16;
pub type uint_least32_t = u32;
pub type uint_least64_t = u64;
pub type int_fast8_t = i8;
pub type int_fast16_t = i16;
pub type int_fast32_t = i32;
pub type int_fast64_t = i64;
pub type uint_fast8_t = u8;
pub type uint_fast16_t = u16;
pub type uint_fast32_t = u32;
pub type uint_fast64_t = u64;
pub type __int8_t = ::core::ffi::c_schar;
pub type __uint8_t = ::core::ffi::c_uchar;
pub type __int16_t = ::core::ffi::c_short;
pub type __uint16_t = ::core::ffi::c_ushort;
pub type __int32_t = ::core::ffi::c_int;
pub type __uint32_t = ::core::ffi::c_uint;
pub type __int64_t = ::core::ffi::c_longlong;
pub type __uint64_t = ::core::ffi::c_ulonglong;
pub type __darwin_intptr_t = ::core::ffi::c_long;
pub type __darwin_natural_t = ::core::ffi::c_uint;
pub type __darwin_ct_rune_t = ::core::ffi::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union __mbstate_t {
    pub __mbstate8: [::core::ffi::c_char; 128usize],
    pub _mbstateL: ::core::ffi::c_longlong,
}
pub type __darwin_mbstate_t = __mbstate_t;
pub type __darwin_ptrdiff_t = ::core::ffi::c_long;
pub type __darwin_size_t = ::core::ffi::c_ulong;
pub type __darwin_va_list = __builtin_va_list;
pub type __darwin_wchar_t = ::core::ffi::c_int;
pub type __darwin_rune_t = __darwin_wchar_t;
pub type __darwin_wint_t = ::core::ffi::c_int;
pub type __darwin_clock_t = ::core::ffi::c_ulong;
pub type __darwin_socklen_t = __uint32_t;
pub type __darwin_ssize_t = ::core::ffi::c_long;
pub type __darwin_time_t = ::core::ffi::c_long;
pub type __darwin_blkcnt_t = __int64_t;
pub type __darwin_blksize_t = __int32_t;
pub type __darwin_dev_t = __int32_t;
pub type __darwin_fsblkcnt_t = ::core::ffi::c_uint;
pub type __darwin_fsfilcnt_t = ::core::ffi::c_uint;
pub type __darwin_gid_t = __uint32_t;
pub type __darwin_id_t = __uint32_t;
pub type __darwin_ino64_t = __uint64_t;
pub type __darwin_ino_t = __darwin_ino64_t;
pub type __darwin_mach_port_name_t = __darwin_natural_t;
pub type __darwin_mach_port_t = __darwin_mach_port_name_t;
pub type __darwin_mode_t = __uint16_t;
pub type __darwin_off_t = __int64_t;
pub type __darwin_pid_t = __int32_t;
pub type __darwin_sigset_t = __uint32_t;
pub type __darwin_suseconds_t = __int32_t;
pub type __darwin_uid_t = __uint32_t;
pub type __darwin_useconds_t = __uint32_t;
pub type __darwin_uuid_t = [::core::ffi::c_uchar; 16usize];
pub type __darwin_uuid_string_t = [::core::ffi::c_char; 37usize];
pub type intmax_t = ::core::ffi::c_long;
pub type uintmax_t = ::core::ffi::c_ulong;
pub type rsize_t = ::core::ffi::c_ulong;
pub type wchar_t = ::core::ffi::c_int;
pub type max_align_t = f64;
pub type bfloat16_t = u16;
pub type float32_t = f32;
pub type float16_t = __BindgenFloat16;
pub type float64_t = f64;
pub type poly8_t = u8;
pub type poly16_t = u16;
pub type poly64_t = u64;
pub type poly128_t = __uint128_t;
pub type int8x8_t = [i8; 8usize];
pub type int8x16_t = [i8; 16usize];
pub type int16x4_t = [i16; 4usize];
pub type int16x8_t = [i16; 8usize];
pub type int32x2_t = [i32; 2usize];
pub type int32x4_t = [i32; 4usize];
pub type int64x1_t = [i64; 1usize];
pub type int64x2_t = [i64; 2usize];
pub type uint8x8_t = [u8; 8usize];
pub type uint8x16_t = [u8; 16usize];
pub type uint16x4_t = [u16; 4usize];
pub type uint16x8_t = [u16; 8usize];
pub type uint32x2_t = [u32; 2usize];
pub type uint32x4_t = [u32; 4usize];
pub type uint64x1_t = [u64; 1usize];
pub type uint64x2_t = [u64; 2usize];
pub type float16x4_t = [float16_t; 4usize];
pub type float16x8_t = [float16_t; 8usize];
pub type float32x2_t = [float32_t; 2usize];
pub type float32x4_t = [float32_t; 4usize];
pub type float64x1_t = [float64_t; 1usize];
pub type float64x2_t = [float64_t; 2usize];
pub type poly8x8_t = [poly8_t; 8usize];
pub type poly8x16_t = [poly8_t; 16usize];
pub type poly16x4_t = [poly16_t; 4usize];
pub type poly16x8_t = [poly16_t; 8usize];
pub type poly64x1_t = [poly64_t; 1usize];
pub type poly64x2_t = [poly64_t; 2usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct int8x8x2_t {
    pub val: [int8x8_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct int8x16x2_t {
    pub val: [int8x16_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct int16x4x2_t {
    pub val: [int16x4_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct int16x8x2_t {
    pub val: [int16x8_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct int32x2x2_t {
    pub val: [int32x2_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct int32x4x2_t {
    pub val: [int32x4_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct int64x1x2_t {
    pub val: [int64x1_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct int64x2x2_t {
    pub val: [int64x2_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint8x8x2_t {
    pub val: [uint8x8_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct uint8x16x2_t {
    pub val: [uint8x16_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint16x4x2_t {
    pub val: [uint16x4_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct uint16x8x2_t {
    pub val: [uint16x8_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint32x2x2_t {
    pub val: [uint32x2_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct uint32x4x2_t {
    pub val: [uint32x4_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint64x1x2_t {
    pub val: [uint64x1_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct uint64x2x2_t {
    pub val: [uint64x2_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float16x4x2_t {
    pub val: [float16x4_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct float16x8x2_t {
    pub val: [float16x8_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float32x2x2_t {
    pub val: [float32x2_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct float32x4x2_t {
    pub val: [float32x4_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float64x1x2_t {
    pub val: [float64x1_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct float64x2x2_t {
    pub val: [float64x2_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct poly8x8x2_t {
    pub val: [poly8x8_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct poly8x16x2_t {
    pub val: [poly8x16_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct poly16x4x2_t {
    pub val: [poly16x4_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct poly16x8x2_t {
    pub val: [poly16x8_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct poly64x1x2_t {
    pub val: [poly64x1_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct poly64x2x2_t {
    pub val: [poly64x2_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct int8x8x3_t {
    pub val: [int8x8_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct int8x16x3_t {
    pub val: [int8x16_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct int16x4x3_t {
    pub val: [int16x4_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct int16x8x3_t {
    pub val: [int16x8_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct int32x2x3_t {
    pub val: [int32x2_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct int32x4x3_t {
    pub val: [int32x4_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct int64x1x3_t {
    pub val: [int64x1_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct int64x2x3_t {
    pub val: [int64x2_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint8x8x3_t {
    pub val: [uint8x8_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct uint8x16x3_t {
    pub val: [uint8x16_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint16x4x3_t {
    pub val: [uint16x4_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct uint16x8x3_t {
    pub val: [uint16x8_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint32x2x3_t {
    pub val: [uint32x2_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct uint32x4x3_t {
    pub val: [uint32x4_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint64x1x3_t {
    pub val: [uint64x1_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct uint64x2x3_t {
    pub val: [uint64x2_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float16x4x3_t {
    pub val: [float16x4_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct float16x8x3_t {
    pub val: [float16x8_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float32x2x3_t {
    pub val: [float32x2_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct float32x4x3_t {
    pub val: [float32x4_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float64x1x3_t {
    pub val: [float64x1_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct float64x2x3_t {
    pub val: [float64x2_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct poly8x8x3_t {
    pub val: [poly8x8_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct poly8x16x3_t {
    pub val: [poly8x16_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct poly16x4x3_t {
    pub val: [poly16x4_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct poly16x8x3_t {
    pub val: [poly16x8_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct poly64x1x3_t {
    pub val: [poly64x1_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct poly64x2x3_t {
    pub val: [poly64x2_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct int8x8x4_t {
    pub val: [int8x8_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct int8x16x4_t {
    pub val: [int8x16_t; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct int16x4x4_t {
    pub val: [int16x4_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct int16x8x4_t {
    pub val: [int16x8_t; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct int32x2x4_t {
    pub val: [int32x2_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct int32x4x4_t {
    pub val: [int32x4_t; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct int64x1x4_t {
    pub val: [int64x1_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct int64x2x4_t {
    pub val: [int64x2_t; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint8x8x4_t {
    pub val: [uint8x8_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct uint8x16x4_t {
    pub val: [uint8x16_t; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint16x4x4_t {
    pub val: [uint16x4_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct uint16x8x4_t {
    pub val: [uint16x8_t; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint32x2x4_t {
    pub val: [uint32x2_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct uint32x4x4_t {
    pub val: [uint32x4_t; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint64x1x4_t {
    pub val: [uint64x1_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct uint64x2x4_t {
    pub val: [uint64x2_t; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float16x4x4_t {
    pub val: [float16x4_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct float16x8x4_t {
    pub val: [float16x8_t; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float32x2x4_t {
    pub val: [float32x2_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct float32x4x4_t {
    pub val: [float32x4_t; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float64x1x4_t {
    pub val: [float64x1_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct float64x2x4_t {
    pub val: [float64x2_t; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct poly8x8x4_t {
    pub val: [poly8x8_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct poly8x16x4_t {
    pub val: [poly8x16_t; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct poly16x4x4_t {
    pub val: [poly16x4_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct poly16x8x4_t {
    pub val: [poly16x8_t; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct poly64x1x4_t {
    pub val: [poly64x1_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct poly64x2x4_t {
    pub val: [poly64x2_t; 4usize],
}
pub type bfloat16x4_t = [bfloat16_t; 4usize];
pub type bfloat16x8_t = [bfloat16_t; 8usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bfloat16x4x2_t {
    pub val: [bfloat16x4_t; 2usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct bfloat16x8x2_t {
    pub val: [bfloat16x8_t; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bfloat16x4x3_t {
    pub val: [bfloat16x4_t; 3usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct bfloat16x8x3_t {
    pub val: [bfloat16x8_t; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bfloat16x4x4_t {
    pub val: [bfloat16x4_t; 4usize],
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct bfloat16x8x4_t {
    pub val: [bfloat16x8_t; 4usize],
}
unsafe extern "C" {
    pub static mut CLAY__ELEMENT_DEFINITION_LATCH: u8;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_String {
    pub isStaticallyAllocated: bool,
    pub length: i32,
    pub chars: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_StringSlice {
    pub length: i32,
    pub chars: *const ::core::ffi::c_char,
    pub baseChars: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_Context {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_Arena {
    pub nextAllocation: usize,
    pub capacity: usize,
    pub memory: *mut ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_Dimensions {
    pub width: f32,
    pub height: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_Vector2 {
    pub x: f32,
    pub y: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_Color {
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_BoundingBox {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ElementId {
    pub id: u32,
    pub offset: u32,
    pub baseId: u32,
    pub stringId: Clay_String,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ElementIdArray {
    pub capacity: i32,
    pub length: i32,
    pub internalArray: *mut Clay_ElementId,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_CornerRadius {
    pub topLeft: f32,
    pub topRight: f32,
    pub bottomLeft: f32,
    pub bottomRight: f32,
}
pub const Clay_LayoutDirection_CLAY_LEFT_TO_RIGHT: Clay_LayoutDirection = 0;
pub const Clay_LayoutDirection_CLAY_TOP_TO_BOTTOM: Clay_LayoutDirection = 1;
pub type Clay_LayoutDirection = ::core::ffi::c_uchar;
pub const Clay_LayoutAlignmentX_CLAY_ALIGN_X_LEFT: Clay_LayoutAlignmentX = 0;
pub const Clay_LayoutAlignmentX_CLAY_ALIGN_X_RIGHT: Clay_LayoutAlignmentX = 1;
pub const Clay_LayoutAlignmentX_CLAY_ALIGN_X_CENTER: Clay_LayoutAlignmentX = 2;
pub type Clay_LayoutAlignmentX = ::core::ffi::c_uchar;
pub const Clay_LayoutAlignmentY_CLAY_ALIGN_Y_TOP: Clay_LayoutAlignmentY = 0;
pub const Clay_LayoutAlignmentY_CLAY_ALIGN_Y_BOTTOM: Clay_LayoutAlignmentY = 1;
pub const Clay_LayoutAlignmentY_CLAY_ALIGN_Y_CENTER: Clay_LayoutAlignmentY = 2;
pub type Clay_LayoutAlignmentY = ::core::ffi::c_uchar;
pub const Clay__SizingType_CLAY__SIZING_TYPE_FIT: Clay__SizingType = 0;
pub const Clay__SizingType_CLAY__SIZING_TYPE_GROW: Clay__SizingType = 1;
pub const Clay__SizingType_CLAY__SIZING_TYPE_PERCENT: Clay__SizingType = 2;
pub const Clay__SizingType_CLAY__SIZING_TYPE_FIXED: Clay__SizingType = 3;
pub type Clay__SizingType = ::core::ffi::c_uchar;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ChildAlignment {
    pub x: Clay_LayoutAlignmentX,
    pub y: Clay_LayoutAlignmentY,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_SizingMinMax {
    pub min: f32,
    pub max: f32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Clay_SizingAxis {
    pub size: Clay_SizingAxis__bindgen_ty_1,
    pub type_: Clay__SizingType,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union Clay_SizingAxis__bindgen_ty_1 {
    pub minMax: Clay_SizingMinMax,
    pub percent: f32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Clay_Sizing {
    pub width: Clay_SizingAxis,
    pub height: Clay_SizingAxis,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_Padding {
    pub left: u16,
    pub right: u16,
    pub top: u16,
    pub bottom: u16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay__Clay_PaddingWrapper {
    pub wrapped: Clay_Padding,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Clay_LayoutConfig {
    pub sizing: Clay_Sizing,
    pub padding: Clay_Padding,
    pub childGap: u16,
    pub childAlignment: Clay_ChildAlignment,
    pub layoutDirection: Clay_LayoutDirection,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Clay__Clay_LayoutConfigWrapper {
    pub wrapped: Clay_LayoutConfig,
}
unsafe extern "C" {
    pub static mut CLAY_LAYOUT_DEFAULT: Clay_LayoutConfig;
}
pub const Clay_TextElementConfigWrapMode_CLAY_TEXT_WRAP_WORDS: Clay_TextElementConfigWrapMode = 0;
pub const Clay_TextElementConfigWrapMode_CLAY_TEXT_WRAP_NEWLINES: Clay_TextElementConfigWrapMode =
    1;
pub const Clay_TextElementConfigWrapMode_CLAY_TEXT_WRAP_NONE: Clay_TextElementConfigWrapMode = 2;
pub type Clay_TextElementConfigWrapMode = ::core::ffi::c_uchar;
pub const Clay_TextAlignment_CLAY_TEXT_ALIGN_LEFT: Clay_TextAlignment = 0;
pub const Clay_TextAlignment_CLAY_TEXT_ALIGN_CENTER: Clay_TextAlignment = 1;
pub const Clay_TextAlignment_CLAY_TEXT_ALIGN_RIGHT: Clay_TextAlignment = 2;
pub type Clay_TextAlignment = ::core::ffi::c_uchar;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_TextElementConfig {
    pub userData: *mut ::core::ffi::c_void,
    pub textColor: Clay_Color,
    pub fontId: u16,
    pub fontSize: u16,
    pub letterSpacing: u16,
    pub lineHeight: u16,
    pub wrapMode: Clay_TextElementConfigWrapMode,
    pub textAlignment: Clay_TextAlignment,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay__Clay_TextElementConfigWrapper {
    pub wrapped: Clay_TextElementConfig,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_AspectRatioElementConfig {
    pub aspectRatio: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay__Clay_AspectRatioElementConfigWrapper {
    pub wrapped: Clay_AspectRatioElementConfig,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ImageElementConfig {
    pub imageData: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay__Clay_ImageElementConfigWrapper {
    pub wrapped: Clay_ImageElementConfig,
}
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_LEFT_TOP: Clay_FloatingAttachPointType = 0;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_LEFT_CENTER: Clay_FloatingAttachPointType =
    1;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_LEFT_BOTTOM: Clay_FloatingAttachPointType =
    2;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_CENTER_TOP: Clay_FloatingAttachPointType =
    3;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_CENTER_CENTER:
    Clay_FloatingAttachPointType = 4;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_CENTER_BOTTOM:
    Clay_FloatingAttachPointType = 5;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_RIGHT_TOP: Clay_FloatingAttachPointType =
    6;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_RIGHT_CENTER:
    Clay_FloatingAttachPointType = 7;
pub const Clay_FloatingAttachPointType_CLAY_ATTACH_POINT_RIGHT_BOTTOM:
    Clay_FloatingAttachPointType = 8;
pub type Clay_FloatingAttachPointType = ::core::ffi::c_uchar;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_FloatingAttachPoints {
    pub element: Clay_FloatingAttachPointType,
    pub parent: Clay_FloatingAttachPointType,
}
pub const Clay_PointerCaptureMode_CLAY_POINTER_CAPTURE_MODE_CAPTURE: Clay_PointerCaptureMode = 0;
pub const Clay_PointerCaptureMode_CLAY_POINTER_CAPTURE_MODE_PASSTHROUGH: Clay_PointerCaptureMode =
    1;
pub type Clay_PointerCaptureMode = ::core::ffi::c_uchar;
pub const Clay_FloatingAttachToElement_CLAY_ATTACH_TO_NONE: Clay_FloatingAttachToElement = 0;
pub const Clay_FloatingAttachToElement_CLAY_ATTACH_TO_PARENT: Clay_FloatingAttachToElement = 1;
pub const Clay_FloatingAttachToElement_CLAY_ATTACH_TO_ELEMENT_WITH_ID:
    Clay_FloatingAttachToElement = 2;
pub const Clay_FloatingAttachToElement_CLAY_ATTACH_TO_ROOT: Clay_FloatingAttachToElement = 3;
pub type Clay_FloatingAttachToElement = ::core::ffi::c_uchar;
pub const Clay_FloatingClipToElement_CLAY_CLIP_TO_NONE: Clay_FloatingClipToElement = 0;
pub const Clay_FloatingClipToElement_CLAY_CLIP_TO_ATTACHED_PARENT: Clay_FloatingClipToElement = 1;
pub type Clay_FloatingClipToElement = ::core::ffi::c_uchar;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_FloatingElementConfig {
    pub offset: Clay_Vector2,
    pub expand: Clay_Dimensions,
    pub parentId: u32,
    pub zIndex: i16,
    pub attachPoints: Clay_FloatingAttachPoints,
    pub pointerCaptureMode: Clay_PointerCaptureMode,
    pub attachTo: Clay_FloatingAttachToElement,
    pub clipTo: Clay_FloatingClipToElement,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay__Clay_FloatingElementConfigWrapper {
    pub wrapped: Clay_FloatingElementConfig,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_CustomElementConfig {
    pub customData: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay__Clay_CustomElementConfigWrapper {
    pub wrapped: Clay_CustomElementConfig,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ClipElementConfig {
    pub horizontal: bool,
    pub vertical: bool,
    pub childOffset: Clay_Vector2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay__Clay_ClipElementConfigWrapper {
    pub wrapped: Clay_ClipElementConfig,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_BorderWidth {
    pub left: u16,
    pub right: u16,
    pub top: u16,
    pub bottom: u16,
    pub betweenChildren: u16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_BorderElementConfig {
    pub color: Clay_Color,
    pub width: Clay_BorderWidth,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay__Clay_BorderElementConfigWrapper {
    pub wrapped: Clay_BorderElementConfig,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_TransitionData {
    pub boundingBox: Clay_BoundingBox,
    pub backgroundColor: Clay_Color,
    pub overlayColor: Clay_Color,
    pub borderColor: Clay_Color,
    pub borderWidth: Clay_BorderWidth,
}
pub const Clay_TransitionState_CLAY_TRANSITION_STATE_IDLE: Clay_TransitionState = 0;
pub const Clay_TransitionState_CLAY_TRANSITION_STATE_ENTERING: Clay_TransitionState = 1;
pub const Clay_TransitionState_CLAY_TRANSITION_STATE_TRANSITIONING: Clay_TransitionState = 2;
pub const Clay_TransitionState_CLAY_TRANSITION_STATE_EXITING: Clay_TransitionState = 3;
pub type Clay_TransitionState = ::core::ffi::c_uint;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_NONE: Clay_TransitionProperty = 0;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_X: Clay_TransitionProperty = 1;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_Y: Clay_TransitionProperty = 2;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_POSITION: Clay_TransitionProperty = 3;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_WIDTH: Clay_TransitionProperty = 4;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_HEIGHT: Clay_TransitionProperty = 8;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_DIMENSIONS: Clay_TransitionProperty = 12;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_BOUNDING_BOX: Clay_TransitionProperty =
    15;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_BACKGROUND_COLOR:
    Clay_TransitionProperty = 16;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_OVERLAY_COLOR: Clay_TransitionProperty =
    32;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_CORNER_RADIUS: Clay_TransitionProperty =
    64;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_BORDER_COLOR: Clay_TransitionProperty =
    128;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_BORDER_WIDTH: Clay_TransitionProperty =
    256;
pub const Clay_TransitionProperty_CLAY_TRANSITION_PROPERTY_BORDER: Clay_TransitionProperty = 384;
pub type Clay_TransitionProperty = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_TransitionCallbackArguments {
    pub transitionState: Clay_TransitionState,
    pub initial: Clay_TransitionData,
    pub current: *mut Clay_TransitionData,
    pub target: Clay_TransitionData,
    pub elapsedTime: f32,
    pub duration: f32,
    pub properties: Clay_TransitionProperty,
}
pub const Clay_TransitionEnterTriggerType_CLAY_TRANSITION_ENTER_SKIP_ON_FIRST_PARENT_FRAME:
    Clay_TransitionEnterTriggerType = 0;
pub const Clay_TransitionEnterTriggerType_CLAY_TRANSITION_ENTER_TRIGGER_ON_FIRST_PARENT_FRAME:
    Clay_TransitionEnterTriggerType = 1;
pub type Clay_TransitionEnterTriggerType = ::core::ffi::c_uchar;
pub const Clay_TransitionExitTriggerType_CLAY_TRANSITION_EXIT_SKIP_WHEN_PARENT_EXITS:
    Clay_TransitionExitTriggerType = 0;
pub const Clay_TransitionExitTriggerType_CLAY_TRANSITION_EXIT_TRIGGER_WHEN_PARENT_EXITS:
    Clay_TransitionExitTriggerType = 1;
pub type Clay_TransitionExitTriggerType = ::core::ffi::c_uchar;
pub const Clay_TransitionInteractionHandlingType_CLAY_TRANSITION_DISABLE_INTERACTIONS_WHILE_TRANSITIONING_POSITION : Clay_TransitionInteractionHandlingType = 0 ;
pub const Clay_TransitionInteractionHandlingType_CLAY_TRANSITION_ALLOW_INTERACTIONS_WHILE_TRANSITIONING_POSITION : Clay_TransitionInteractionHandlingType = 1 ;
pub type Clay_TransitionInteractionHandlingType = ::core::ffi::c_uchar;
pub const Clay_ExitTransitionSiblingOrdering_CLAY_EXIT_TRANSITION_ORDERING_UNDERNEATH_SIBLINGS:
    Clay_ExitTransitionSiblingOrdering = 0;
pub const Clay_ExitTransitionSiblingOrdering_CLAY_EXIT_TRANSITION_ORDERING_NATURAL_ORDER:
    Clay_ExitTransitionSiblingOrdering = 1;
pub const Clay_ExitTransitionSiblingOrdering_CLAY_EXIT_TRANSITION_ORDERING_ABOVE_SIBLINGS:
    Clay_ExitTransitionSiblingOrdering = 2;
pub type Clay_ExitTransitionSiblingOrdering = ::core::ffi::c_uchar;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_TransitionElementConfig {
    pub handler: ::core::option::Option<
        unsafe extern "C" fn(arguments: Clay_TransitionCallbackArguments) -> bool,
    >,
    pub duration: f32,
    pub properties: Clay_TransitionProperty,
    pub interactionHandling: Clay_TransitionInteractionHandlingType,
    pub enter: Clay_TransitionElementConfig__bindgen_ty_1,
    pub exit: Clay_TransitionElementConfig__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_TransitionElementConfig__bindgen_ty_1 {
    pub setInitialState: ::core::option::Option<
        unsafe extern "C" fn(
            targetState: Clay_TransitionData,
            properties: Clay_TransitionProperty,
        ) -> Clay_TransitionData,
    >,
    pub trigger: Clay_TransitionEnterTriggerType,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_TransitionElementConfig__bindgen_ty_2 {
    pub setFinalState: ::core::option::Option<
        unsafe extern "C" fn(
            initialState: Clay_TransitionData,
            properties: Clay_TransitionProperty,
        ) -> Clay_TransitionData,
    >,
    pub trigger: Clay_TransitionExitTriggerType,
    pub siblingOrdering: Clay_ExitTransitionSiblingOrdering,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay__Clay_TransitionElementConfigWrapper {
    pub wrapped: Clay_TransitionElementConfig,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_TextRenderData {
    pub stringContents: Clay_StringSlice,
    pub textColor: Clay_Color,
    pub fontId: u16,
    pub fontSize: u16,
    pub letterSpacing: u16,
    pub lineHeight: u16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_RectangleRenderData {
    pub backgroundColor: Clay_Color,
    pub cornerRadius: Clay_CornerRadius,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ImageRenderData {
    pub backgroundColor: Clay_Color,
    pub cornerRadius: Clay_CornerRadius,
    pub imageData: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_CustomRenderData {
    pub backgroundColor: Clay_Color,
    pub cornerRadius: Clay_CornerRadius,
    pub customData: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ClipRenderData {
    pub horizontal: bool,
    pub vertical: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_OverlayColorRenderData {
    pub color: Clay_Color,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_BorderRenderData {
    pub color: Clay_Color,
    pub cornerRadius: Clay_CornerRadius,
    pub width: Clay_BorderWidth,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union Clay_RenderData {
    pub rectangle: Clay_RectangleRenderData,
    pub text: Clay_TextRenderData,
    pub image: Clay_ImageRenderData,
    pub custom: Clay_CustomRenderData,
    pub border: Clay_BorderRenderData,
    pub clip: Clay_ClipRenderData,
    pub overlayColor: Clay_OverlayColorRenderData,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ScrollContainerData {
    pub scrollPosition: *mut Clay_Vector2,
    pub scrollContainerDimensions: Clay_Dimensions,
    pub contentDimensions: Clay_Dimensions,
    pub config: Clay_ClipElementConfig,
    pub found: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ElementData {
    pub boundingBox: Clay_BoundingBox,
    pub found: bool,
}
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_NONE: Clay_RenderCommandType = 0;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_RECTANGLE: Clay_RenderCommandType = 1;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_BORDER: Clay_RenderCommandType = 2;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_TEXT: Clay_RenderCommandType = 3;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_IMAGE: Clay_RenderCommandType = 4;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_SCISSOR_START: Clay_RenderCommandType = 5;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_SCISSOR_END: Clay_RenderCommandType = 6;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_OVERLAY_COLOR_START:
    Clay_RenderCommandType = 7;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_OVERLAY_COLOR_END:
    Clay_RenderCommandType = 8;
pub const Clay_RenderCommandType_CLAY_RENDER_COMMAND_TYPE_CUSTOM: Clay_RenderCommandType = 9;
pub type Clay_RenderCommandType = ::core::ffi::c_uchar;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Clay_RenderCommand {
    pub boundingBox: Clay_BoundingBox,
    pub renderData: Clay_RenderData,
    pub userData: *mut ::core::ffi::c_void,
    pub id: u32,
    pub zIndex: i16,
    pub commandType: Clay_RenderCommandType,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_RenderCommandArray {
    pub capacity: i32,
    pub length: i32,
    pub internalArray: *mut Clay_RenderCommand,
}
pub const Clay_PointerDataInteractionState_CLAY_POINTER_DATA_PRESSED_THIS_FRAME:
    Clay_PointerDataInteractionState = 0;
pub const Clay_PointerDataInteractionState_CLAY_POINTER_DATA_PRESSED:
    Clay_PointerDataInteractionState = 1;
pub const Clay_PointerDataInteractionState_CLAY_POINTER_DATA_RELEASED_THIS_FRAME:
    Clay_PointerDataInteractionState = 2;
pub const Clay_PointerDataInteractionState_CLAY_POINTER_DATA_RELEASED:
    Clay_PointerDataInteractionState = 3;
pub type Clay_PointerDataInteractionState = ::core::ffi::c_uchar;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_PointerData {
    pub position: Clay_Vector2,
    pub state: Clay_PointerDataInteractionState,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Clay_ElementDeclaration {
    pub layout: Clay_LayoutConfig,
    pub backgroundColor: Clay_Color,
    pub overlayColor: Clay_Color,
    pub cornerRadius: Clay_CornerRadius,
    pub aspectRatio: Clay_AspectRatioElementConfig,
    pub image: Clay_ImageElementConfig,
    pub floating: Clay_FloatingElementConfig,
    pub custom: Clay_CustomElementConfig,
    pub clip: Clay_ClipElementConfig,
    pub border: Clay_BorderElementConfig,
    pub transition: Clay_TransitionElementConfig,
    pub userData: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Clay__Clay_ElementDeclarationWrapper {
    pub wrapped: Clay_ElementDeclaration,
}
pub const Clay_ErrorType_CLAY_ERROR_TYPE_TEXT_MEASUREMENT_FUNCTION_NOT_PROVIDED: Clay_ErrorType = 0;
pub const Clay_ErrorType_CLAY_ERROR_TYPE_ARENA_CAPACITY_EXCEEDED: Clay_ErrorType = 1;
pub const Clay_ErrorType_CLAY_ERROR_TYPE_ELEMENTS_CAPACITY_EXCEEDED: Clay_ErrorType = 2;
pub const Clay_ErrorType_CLAY_ERROR_TYPE_TEXT_MEASUREMENT_CAPACITY_EXCEEDED: Clay_ErrorType = 3;
pub const Clay_ErrorType_CLAY_ERROR_TYPE_DUPLICATE_ID: Clay_ErrorType = 4;
pub const Clay_ErrorType_CLAY_ERROR_TYPE_FLOATING_CONTAINER_PARENT_NOT_FOUND: Clay_ErrorType = 5;
pub const Clay_ErrorType_CLAY_ERROR_TYPE_PERCENTAGE_OVER_1: Clay_ErrorType = 6;
pub const Clay_ErrorType_CLAY_ERROR_TYPE_INTERNAL_ERROR: Clay_ErrorType = 7;
pub const Clay_ErrorType_CLAY_ERROR_TYPE_UNBALANCED_OPEN_CLOSE: Clay_ErrorType = 8;
pub const Clay_ErrorType_CLAY_ERROR_TYPE_HASH_MAP_CAPACITY_EXCEEDED: Clay_ErrorType = 9;
pub type Clay_ErrorType = ::core::ffi::c_uchar;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ErrorData {
    pub errorType: Clay_ErrorType,
    pub errorText: Clay_String,
    pub userData: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Clay_ErrorHandler {
    pub errorHandlerFunction:
        ::core::option::Option<unsafe extern "C" fn(errorText: Clay_ErrorData)>,
    pub userData: *mut ::core::ffi::c_void,
}
unsafe extern "C" {
    pub fn Clay_MinMemorySize() -> u32;
}
unsafe extern "C" {
    pub fn Clay_CreateArenaWithCapacityAndMemory(
        capacity: usize,
        memory: *mut ::core::ffi::c_void,
    ) -> Clay_Arena;
}
unsafe extern "C" {
    pub fn Clay_SetPointerState(position: Clay_Vector2, pointerDown: bool);
}
unsafe extern "C" {
    pub fn Clay_GetPointerState() -> Clay_PointerData;
}
unsafe extern "C" {
    pub fn Clay_Initialize(
        arena: Clay_Arena,
        layoutDimensions: Clay_Dimensions,
        errorHandler: Clay_ErrorHandler,
    ) -> *mut Clay_Context;
}
unsafe extern "C" {
    pub fn Clay_GetCurrentContext() -> *mut Clay_Context;
}
unsafe extern "C" {
    pub fn Clay_SetCurrentContext(context: *mut Clay_Context);
}
unsafe extern "C" {
    pub fn Clay_UpdateScrollContainers(
        enableDragScrolling: bool,
        scrollDelta: Clay_Vector2,
        deltaTime: f32,
    );
}
unsafe extern "C" {
    pub fn Clay_GetScrollOffset() -> Clay_Vector2;
}
unsafe extern "C" {
    pub fn Clay_SetLayoutDimensions(dimensions: Clay_Dimensions);
}
unsafe extern "C" {
    pub fn Clay_GetLayoutDimensions() -> Clay_Dimensions;
}
unsafe extern "C" {
    pub fn Clay_BeginLayout();
}
unsafe extern "C" {
    pub fn Clay_EndLayout(deltaTime: f32) -> Clay_RenderCommandArray;
}
unsafe extern "C" {
    pub fn Clay_GetOpenElementId() -> u32;
}
unsafe extern "C" {
    pub fn Clay_GetElementId(idString: Clay_String) -> Clay_ElementId;
}
unsafe extern "C" {
    pub fn Clay_GetElementIdWithIndex(idString: Clay_String, index: u32) -> Clay_ElementId;
}
unsafe extern "C" {
    pub fn Clay_GetElementData(id: Clay_ElementId) -> Clay_ElementData;
}
unsafe extern "C" {
    pub fn Clay_Hovered() -> bool;
}
unsafe extern "C" {
    pub fn Clay_OnHover(
        onHoverFunction: ::core::option::Option<
            unsafe extern "C" fn(
                elementId: Clay_ElementId,
                pointerData: Clay_PointerData,
                userData: *mut ::core::ffi::c_void,
            ),
        >,
        userData: *mut ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn Clay_PointerOver(elementId: Clay_ElementId) -> bool;
}
unsafe extern "C" {
    pub fn Clay_GetPointerOverIds() -> Clay_ElementIdArray;
}
unsafe extern "C" {
    pub fn Clay_GetScrollContainerData(id: Clay_ElementId) -> Clay_ScrollContainerData;
}
unsafe extern "C" {
    pub fn Clay_SetMeasureTextFunction(
        measureTextFunction: ::core::option::Option<
            unsafe extern "C" fn(
                text: Clay_StringSlice,
                config: *mut Clay_TextElementConfig,
                userData: *mut ::core::ffi::c_void,
            ) -> Clay_Dimensions,
        >,
        userData: *mut ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn Clay_SetQueryScrollOffsetFunction(
        queryScrollOffsetFunction: ::core::option::Option<
            unsafe extern "C" fn(
                elementId: u32,
                userData: *mut ::core::ffi::c_void,
            ) -> Clay_Vector2,
        >,
        userData: *mut ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn Clay_RenderCommandArray_Get(
        array: *mut Clay_RenderCommandArray,
        index: i32,
    ) -> *mut Clay_RenderCommand;
}
unsafe extern "C" {
    pub fn Clay_SetDebugModeEnabled(enabled: bool);
}
unsafe extern "C" {
    pub fn Clay_IsDebugModeEnabled() -> bool;
}
unsafe extern "C" {
    pub fn Clay_SetCullingEnabled(enabled: bool);
}
unsafe extern "C" {
    pub fn Clay_GetMaxElementCount() -> i32;
}
unsafe extern "C" {
    pub fn Clay_SetMaxElementCount(maxElementCount: i32);
}
unsafe extern "C" {
    pub fn Clay_GetMaxMeasureTextCacheWordCount() -> i32;
}
unsafe extern "C" {
    pub fn Clay_SetMaxMeasureTextCacheWordCount(maxMeasureTextCacheWordCount: i32);
}
unsafe extern "C" {
    pub fn Clay_ResetMeasureTextCache();
}
unsafe extern "C" {
    pub fn Clay_EaseOut(arguments: Clay_TransitionCallbackArguments) -> bool;
}
unsafe extern "C" {
    pub fn Clay__OpenElement();
}
unsafe extern "C" {
    pub fn Clay__OpenElementWithId(elementId: Clay_ElementId);
}
unsafe extern "C" {
    pub fn Clay__ConfigureOpenElement(config: Clay_ElementDeclaration);
}
unsafe extern "C" {
    pub fn Clay__ConfigureOpenElementPtr(config: *const Clay_ElementDeclaration);
}
unsafe extern "C" {
    pub fn Clay__CloseElement();
}
unsafe extern "C" {
    pub fn Clay__HashString(key: Clay_String, seed: u32) -> Clay_ElementId;
}
unsafe extern "C" {
    pub fn Clay__HashStringWithOffset(key: Clay_String, offset: u32, seed: u32) -> Clay_ElementId;
}
unsafe extern "C" {
    pub fn Clay__OpenTextElement(text: Clay_String, textConfig: Clay_TextElementConfig);
}
unsafe extern "C" {
    pub static mut Clay__debugViewHighlightColor: Clay_Color;
}
unsafe extern "C" {
    pub static mut Clay__debugViewWidth: u32;
}
pub type __builtin_va_list = *mut ::core::ffi::c_char;
pub type __uint128_t = u128;
